name: Run a nightly build

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings
  
  upload:
    needs: test
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    runs-on: {{matrix.os}}
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Build (.net)
      run: dotnet build ResolveXmlUnreal/ResolveXmlUnreal.csproj -c Release -o dist
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v2
      with:
        name: Build for ${{matrix.os}}
        path: dist

    