name: Run a nightly build

on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --settings coverlet.runsettings
    
    - name: Build (.net)
      run: dotnet build ResolveXmlUnreal/ResolveXmlUnreal.csproj -c Release -o dist/net
    
    - uses: actions/upload-artifact@v2
      with:
        name: Build
        path: dist/net

    